#!/bin/bash

grep --color=auto -HnR \
	--exclude-dir=.git \
	--exclude-dir=cover \
	--exclude-dir=docs \
	--exclude-dir=build \
	--exclude-dir=tests/test_integration/data \
	--exclude=*.pyc \
	--exclude=*.db \
	--exclude=*.swp "$@"
