#!/bin/bash

vim $(grep -HnRl \
	--exclude-dir=.git \
	--exclude-dir=cover \
	--exclude-dir=docs \
	--exclude-dir=build \
	--exclude-dir=tests/test_integration/data \
	--exclude=*.pyc \
	--exclude=*.swp \
	--exclude=*.db \
	"$@" | sort)
